### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by wtrocki** [feedhenry/fh-sync#4]
Improve README to provide some basic documentation for module

**Comment by aidenkeating** [comment]
@wtrocki In terms of what is already available we have a couple of places that a lot of documentation could be sourced from.

* The wiki on fh-mbaas-api (https://github.com/feedhenry/fh-mbaas-api/wiki).
* The slightly out of date sync section of the deprecated feedhenry-sdk-docs repo (https://github.com/feedhenry/feedhenry-sdk-docs#sync-framework-fhsync).

Also. either using the already existing JSDoc in new sync or the upcoming declaration file we can generate automated docs for sync (using typedoc in TypeScripts case).
